### PR TITLE
Greedy Algorithm -Activity Selection

### PR DESCRIPTION
**Pull request by shailja2727**
# Description
It is classic Greedy Problem .In activity selection problem we always pick the next activity whose finish time is the least among the remaining activities and the start time is more than or equal to the finish time of the previously selected activity. We can sort the activities according to their finishing time so that we always consider the next activity as the minimum finishing time activity
Steps:
i)Sort the activities according to their finishing time
ii)Select the first activity from the sorted array and print it
ii)Do the following for the remaining activities in the sorted array
If the start time of this activity is greater than or equal to the finish time of the previously selected activity then select this activity and print it

Fixes:  #111 
Issue No. #111 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by shailja2727** [comment]
@Sulagna-Dutta-Roy Please check and tell if there's a change needed .I have added the code

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
No need to make C++ folder.
Direct add it to Algorithms/Greedy Activation/your files.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by shailja2727** [comment]
Hi Ma'am,
I just wanted to know the contribution I did ..how will I add it in swoc 23

**Comment by Sulagna-Dutta-Roy** [comment]
You need to submit this PR link in Devfolio of SWOC

**Comment by shailja2727** [comment]
Ok ma'am Thank you

**Pull request merged**
