### PR TITLE
Toplogical sort both approaches added

### PR DESCRIPTION
**Pull request by diyagoyal98**
# Description

I have added Toplogical sort with 2 different approaches .

Fixes:  #115

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [X ] I have made this from my own
- [X ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X ] My changes generate no new warnings

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Both are the same files. Kindly check another PRs.

**Comment by diyagoyal98** [comment]
Ma'am ,Please review the files once again these both files are different .
First file contains DFS modified approach
Second file contains khan's Algorithm approach.

**Comment by Sulagna-Dutta-Roy** [comment]
Please make a folder into it.
Format: Algorithms/Topological Sort/your files

**Comment by diyagoyal98** [comment]
Ma'am, Now i have made a new fresh branch in which i have made changes that are being proposed by you. 
Now please review that pull request .
Here is the link of the new pull request
https://github.com/WeBeginners-Community/DocBook/pull/125#issue-1535793389

**Pull request closed without merging**
