### PR TITLE
Sum of subset Problem

### PR DESCRIPTION
**Pull request by Amit0412**
# Description

This contains the basic idea about "Sum of subset " problem along with the C++ code.
Fixes:  #162 

## Type of change

- [✔ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [✔ ] I have made this from my own
- [✔ ] I have taken help from some online recourses 
- [✔ ] My code follows the style guidelines of this project
- [✔ ] I have performed a self-review of my own code
- [✔ ] I have commented my code, particularly in hard-to-understand areas

# ATTA
GDB online Debugger _ Compiler - Code, Compile, Run, Debug online C, C++ - Google Chrome 1_28_2023 6_32_05 PM
CH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — COMMENTED** [review]
Knapsack project still showing

**Comment by Amit0412** [comment]
Pls see now..I mean u have already merged my knapsack PR...I think it should show correct now.Pls see and tell

**Comment by Sulagna-Dutta-Roy** [comment]
close the knapsack PR

**Comment by Sulagna-Dutta-Roy** [comment]
You're pushing same branch with different codes

**Comment by Amit0412** [comment]
Ok lee mee see.

**Pull request closed without merging**
