### PR TITLE
Priority Scheduling and Round Robin Algorithm

### PR DESCRIPTION
**Pull request by goyalh4164**
# Description

1)Priority scheduling is one of the most common scheduling algorithms in batch systems. Each process is assigned a priority. Process with the highest priority is to be executed first and so on. Processes with the same priority are executed on first come first served basis.
2)Round Robin CPU Algorithm generally focuses on Time Sharing technique. 
The period of time for which a process or job is allowed to run in a pre-emptive method is called time quantum. 

Fixes:  #199 #198 

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS 
Priority Scheduling Output
image
Round Robin Scheduling Algorithm Output
image

### CODE REVIEW

**Comment by goyalh4164** [comment]
@Sulagna-Dutta-Roy Issue completed Kindly take a review.Thanks

**Comment by goyalh4164** [comment]
Both Issues are included in the same PR.Kindly take a review

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
This is a documentation repository.
Also no details there and branches conflicting

**Comment by goyalh4164** [comment]
Ok I will look it in it.

**Comment by goyalh4164** [comment]
closing the PR and will solve this issue as soon as possible

**Pull request closed without merging**
