### PR TITLE
This is the code for Stack Permutation

### PR DESCRIPTION
**Pull request by iianuragii**
# Description

Suppose You are given two arrays A and B of unique elements of size N. Check if array B is a stack permutation of the array A or not.
Stack permutation means that array B can be created from array A using a stack and stack operations.

Fixes:  #(issue no.)

#191

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by iianuragii** [comment]
I have given the code already, please merge it

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
This is a documentation repository. Kindly add the details over there

**Comment by iianuragii** [comment]
> This is a documentation repository. Kindly add the details over there

Done

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please add the details it's a documentation repository

**Comment by iianuragii** [comment]
> Please add the details it's a documentation repository

Sorry but I am not getting your point. Can you please tell me where should I give the details?

**Pull request closed without merging**
