### PR TITLE
Documentation of Travelling Salesman Problem (TSP)

### PR DESCRIPTION
**Pull request by viveksondhiya**
# Description
Travelling Salesman Problem
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)
#209 

## Type of change
Added the Documentation of the Travelling Salesman Problem along with the Implementation 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✔️ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [✔️ ] I have made this from my own
- [ ✔️] I have taken help from some online resourses 
- [ ✔️] My code follows the style guidelines of this project
- [ ✔️] I have performed a self-review of my own code 
- [✔️ ] I have made corresponding changes to the documentation
- [ ✔️] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Review by viveksondhiya — COMMENTED** [review]
Task done

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
I can see the selection sort,quick sort files also. Some code files there.
Kindly check it

**Comment by Sulagna-Dutta-Roy** [comment]
This is travelling salesman problem right? 
Then why I can see quick,selection sorts

**Comment by viveksondhiya** [comment]
> This is travelling salesman problem right? Then why I can see quick,selection sorts
i also don't know why they are appearing..

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
