### PR TITLE
FIFO Algorithm

### PR DESCRIPTION
**Pull request by goyalh4164**
# Description

This is the simplest page replacement algorithm. In this algorithm, the operating system keeps track of all pages in the memory in a queue, the oldest page is in the front of the queue. When a page needs to be replaced page in the front of the queue is selected for removal. 

Fixes:  #201 

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS
image

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Mention the correct Issue.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
This is the documentation repository. 
Make sure to add details not coding

**Comment by goyalh4164** [comment]
@Sulagna-Dutta-Roy Do we need to create a separate README file for the documentation

**Comment by goyalh4164** [comment]
> @Sulagna-Dutta-Roy Do we need to create a separate README file for the documentation

?

**Comment by Sulagna-Dutta-Roy** [comment]
This is a documentation repository. Already I mentioned 
No codes here,check other PRs

**Comment by goyalh4164** [comment]
OK I will look into it

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by goyalh4164** [comment]
Thanks for merging 😅😅

**Pull request merged**
