### PR TITLE
Bucketsort Documentation

### PR DESCRIPTION
**Pull request by Amit0412**
# Description

This includes the complete explanation of Bucketsort sorting algorithm. It includes basic definition and step by step algo explanations. 

Fixes:  #121 

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online recourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
DocBook_Algorithms_BucketSort at Bucsrt · Amit0412_DocBook - Google Chrome 1_17_2023 8_56_31 PM

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Format: Algorithms/ Bucket Sort/ your files

**Comment by Amit0412** [comment]
Ok I will do the respective change.

**Comment by Amit0412** [comment]
What changes u r suggesting could u pls explain? I mean I have created a new branch and in Algorithms folder I have created bucket sort named folder and inside that bucketsort.md file

**Comment by Amit0412** [comment]
Kindly pls see..I have done the respective changes...

**Comment by Amit0412** [comment]
When will this PR be merged?..I had made the changes..Thankyou

**Comment by Amit0412** [comment]
Please look this PR also.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
